web/forms/company.py
from .base import BaseValidator

company_create_form = BaseValidator('company_create_form', {

})
company_update_form = BaseValidator('company_update_form', {

})

web/views/company.py
from flask import Blueprint, render_template, request, abort, views, redirect, url_for, abort, flash, send_file
from flask_login import login_required, current_user, login_user
from werkzeug import secure_filename
from io import BytesIO
import xlsxwriter
from flask import current_app as app
from flask_babel import lazy_gettext

import database.models as models
from web import db, form_checker, role_manager, ds
from web.core import constants, geo
import database.enums as db_enums
from role import role_constants

bp = Blueprint('company', __name__)

# Disabled - not allowing creating new company at the moment
# HShould be andled instead by views in register

@bp.route('/create-company')
@login_required
def create_company():
    # Check if user already has a linked company
    #if current_user.is_authenticated:  # checked by decorator
    user = db.user.get_by_id(current_user.get_id())
    if user.company_id: # Company already associated with user
        # user.company_name is used for verification purpose
        return redirect(url_for('company.my_company'))
    
    return render_template('company/create_company.html')

# updating current company associated with user
@bp.route('/my-company/update')
@login_required
def update_company_rv():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))

    # Have permission to access page
    if not role_manager.check_permission(user_id, 
                role_constants.OPERATION_COMPANY, 
                role_constants.ACTION_UPDATE):
        return redirect(url_for('company.my_company'))
    
    company_info = user.company.to_dict()

    return render_template('company/update_company_rv.html', my_company=company_info)

# Company associated to the current user
@bp.route('/my-company')
@login_required
def my_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))
        
    # Obtaining company information
    company = user.company
    #company_info = company.to_dict()
    
    # Checking for editing permission
    company_is_editable = False

    if role_manager.check_permission(user_id, 
                role_constants.OPERATION_COMPANY, 
                role_constants.ACTION_UPDATE):
        company_is_editable = True
   
    # Obtaining employee lists
    #employees = company.users  
    #employee_list = [ employee.to_public_dict() for employee in employees ]    

    first_level_categories = db.product_category.get_first_levels()
  
    return render_template('company/my_company_rv.html', 
        company=company, 
        company_is_editable=company_is_editable,
        datatype="company",
        first_level_categories=first_level_categories)
        #, employee_list=employee_list)


# Specific company by ID with full rendering in template - grouped for public and internal views
@bp.route('/company/<id_slug(model="company"):pr_id>')
def company_page(pr_id):
    is_company_emp = False
    company = db.company.get_by_id(pr_id)
    if not company:
        return abort(404)

    if current_user.is_authenticated:
        user_id = current_user.get_id()
        user = db.user.get_by_id(user_id)
        if user.company_id == company.id:
            is_company_emp = True
        
    if (not company.is_public) and (not is_company_emp):
        return abort(404)

    args = form_checker.process(request)
    current_tab = args.get('tab', 'home')
    
    return render_template('company/company_rv.html', 
        company=company, current_tab=current_tab)


@bp.route('/change-company-role', methods=['GET'])
@login_required
def change_company_role():
    return render_template('company/change_company_role.html')


@bp.route('/link-my-company')
@login_required
def link_my_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)

    if role_manager.is_master(user_id):
        return redirect(url_for('admin.user_master'))

    if user.company_id:
        return redirect(url_for('company.my_company'))

    args = form_checker.process(request, 'company_search_link_form')

    ref_company_id = args.pop('cid', None)
    ref_user_id = args.pop('uid', None)
    # TBI do something with ref_user_id? Notify when user joined
  
    if ref_company_id:
        # There are referrals
        if user.company_id: # User already in a company            
            if int(ref_company_id) == user.company_id:
                # Redirect to its own company
                return redirect(url_for('company.my_company'))
            else:
                # Leave old company and go to a new one
                company_old = db.company.get_by_id(user.company_id).to_public_dict()

                list_companies = [ (db.company.get_by_id(ref_company_id).to_public_dict()) ]
                
                return render_template('company/link_my_company.html', list_companies=list_companies,
                    current_page=1,
                    num_results=1,
                    num_pages=1, 
                    company_old=company_old)

        else:
            list_companies = [ (db.company.get_by_id(ref_company_id).to_public_dict()) ]
            return render_template('company/link_my_company.html', list_companies=list_companies,
                current_page=1,
                num_results=1,
                num_pages=1)
    # No referral or existing company case

    # Add form checker
    # Default type
    limit = int(args.pop('limit', 10))
    current_page = int(args.pop('current_page', 1))
    search_term = args.pop('search_term', '')

    list_companies = []
    if search_term.isdigit():
        # Search based on id
        try:
            list_companies = [ db.company.get_by_id(int(search_term)).to_public_dict() ]
        except ValueError:
            pass

    num_pages, companies, num_results = db.company.search(keyword=search_term, limit=limit, 
            current_page=current_page)
    
    list_companies = list_companies + [ comp.to_public_dict() for comp in companies ]
    pending_request = None

    # Obtain user's pending request
    if user.company_name:
        existing = db.role.filter_by(user_id=user_id, 
            operation=role_constants.OPERATION_GENERAL,
            permission=role_constants.REQUEST_PENDING)
            # Currently overwriting request
        pending_request = existing if existing else None


    return render_template('company/link_my_company.html', list_companies=list_companies,
        current_page=current_page,
        num_results=num_results,
        num_pages=num_pages,
        pending_request=pending_request)
    
    
@bp.route('/my-company-employees')
@login_required
def get_employee_list():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))
        
    # Checking for editing permission
    if not role_manager.check_permission(user_id, 
                role_constants.OPERATION_USER_MANAGEMENT, 
                role_constants.ACTION_VIEW):
        return abort(403) # Access denied
    
    # Obtaining employee lists
    company = user.company
    #employees = company.users 

    pending_requests = []
    
    employees_list = db.role.filter_by_q(company_id=user.company_id,
                    operation=role_constants.OPERATION_GENERAL).filter(
                    models.UserCompanyRole.permission >= role_constants.PERMISSION_ROLE_USER)
    employees = [ emp.to_user_dict() for emp in employees_list]
    
    # Limit permission levels
    current_user_permission = role_manager.get_permission_level(user_id)
    if current_user_permission >= role_constants.PERMISSION_ROLE_MANAGER:
        current_user_permission == role_manager.check_permission(user_id, 
                role_constants.OPERATION_USER_MANAGEMENT,
                role_constants.ACTION_UPDATE)
        # Obtain only verified email
        #pending_requests = (db.user.query().filter_by(company_name=str(company.id),company_id=None,is_account_confirmed=True)
        #)
        #pending_requests = (db.user.query().filter_by(company_name=str(company.id),company_id=None,is_account_confirmed=True)
        #        .join(models.UserCompanyRole).group_by(models.User))#.order_by(models.UserCompanyRole.create_time))
        pending = db.role.filter_by_q(company_id=user.company_id,operation=role_constants.OPERATION_GENERAL,
                permission=role_constants.REQUEST_PENDING).order_by('user_company_role.create_time desc')
                #.join(models.User).group_by(models.User)
        pending_requests = [ (req.user, req.create_time) for req in pending ]

    #employee_list = [ employee.to_public_dict() for employee in employees ]    
    return render_template('company/my_company_employees_rv.html', 
            company=company, 
            employees=employees, 
            permission_levels=role_constants.PERMISSION_TEXT_ARR,
            current_user_permission=current_user_permission,
            pending_requests=pending_requests)
    
    
@bp.route('/verify-company')
@login_required
def verify_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    company = user.company
    company_id = None
    verified = False

    if company:
        company_id = company.id
    else:
        company_id = user.company_name # user that have submitted link request
    
    if not company_id:
        return redirect(url_for('company.link_my_company'))

    company_verify = db.company_verify.filter_by(company_id=company_id)

    submitted_by_user = False # Check if current user has ever submitted a verify request

web/views/home.py
import os
from flask import render_template, Blueprint, redirect, url_for, flash, request
from flask import current_app as app
from flask_login import current_user, login_required
from flask_babel import lazy_gettext
from web import db, form_checker

from sqlalchemy.sql.expression import func

bp = Blueprint('home', __name__)

@bp.route('/')
def default():
    if current_user.is_authenticated:
        if current_user.company_id and current_user.company.products.count() > 0:
            default_view = 'sell'
        else:
            default_view = 'buy'
        view = request.args.get('view', default_view).lower()
        return authenticated_homepage(view=view)

    return generic_homepage()

@bp.route('/index')
def generic_homepage():
    featured_products = db.product.query().order_by(func.random()).limit(3).all()
    newest_products = (db.product.query()
        .order_by(func.random())
        .order_by('product.create_time desc').limit(10).all()
    )
    top_companies = db.company.query().order_by(func.random()).limit(10).all()

    _, newest_rfqs = db.rfq.search(limit=10)

    cats = ['Agriculture', 'Apparel', 'Chemicals', 'Consumer Electronics','Food & Beverage',
        'Furniture', 'Machinery']
    
    cats_with_id = (
        db.query(db.product_category.Model.id, db.product_category.Model.name)
        .filter(db.product_category.Model.name.in_(cats))
        .all()
    )
    cats_dict = {cat:id for id,cat in cats_with_id}

    top_countries = [
        ('us', 'United States'),
        ('cn', 'China'),
        ('vn', 'Vietnam'),
        ('in', 'India'),
        ('hk', 'Hong Kong'),
        ('th', 'Thailand'),
        ('kr', 'Korea'),
        ('jp', 'Japan'),
        ('id', 'Indonesia'),
        ('bd', 'Bangladesh'),
        ('tw', 'Taiwan'),
        ('sg', 'Singapore')
    ]
    
    return render_template('home/index.html',
        featured_products=featured_products,        
        top_companies=top_companies,
        newest_products=newest_products,
        newest_rfqs=newest_rfqs,
        cats_with_id=cats_with_id,
        cats_dict=cats_dict,
        top_countries=top_countries
    )


@bp.route('/my-homepage')
@login_required
def authenticated_homepage(view='buy'):
    if current_user.company_id and current_user.company.products.count() > 0:
        default_view = 'sell'
    else:
        default_view = 'buy'

    view = view or request.args.get('view', default_view).lower()
    contacts = db.thread.get_user_contacts(current_user)
    company = current_user.company if current_user.company_id else None

    if current_user.company_id:
        most_viewed_products = db.product.filter_by(company_id=current_user.company_id, limit=10)
    else:
        most_viewed_products = []
    
    rfqs = db.rfq.filter_by(buyer_id=current_user.id, limit=5)
    quotes = db.quote.filter_by(seller_id=current_user.id, limit=5)

    search_history = db.product.query().order_by(func.random()).limit(10).all()
    recommended_products = db.product.query().order_by(func.random()).limit(10).all()
    
    unread_msgs_count = db.thread.get_total_unread_messages_count(current_user.id)
    threads_with_count = db.thread.get_unread_messages_count_full_thread(current_user.id, limit=5)
    
    return render_template('home/authenticated.html',
        company=company,
        rfqs=rfqs,
        quotes=quotes,
        unread_msgs_count=unread_msgs_count,
        threads_with_count=threads_with_count,
        most_viewed_products=most_viewed_products,
        recommended_products=recommended_products,
        search_history=search_history,
        contacts=contacts,
        view=view
    )



@bp.route('/subscribe', methods=['POST'])
def subscribe():
    args = form_checker.process(request)
    name = args.get('name', None)
    email = args.get('email', None)
    if not name or not email:
        flash(lazy_gettext('Please provide both name and email in the subscriber form'), 'danger')
        return redirect(url_for('home.generic_homepage'))
        
    #TODO SAVE INTO DB INSTEAD OF FILE
    fp = os.path.join(app.parentdir, 'subscribers.txt')
    with open(fp, 'a') as f:
        f.write(f'{name}|{email}\n')

    flash(lazy_gettext('Thank you for subscribing!'), 'success')

    return redirect(url_for('home.generic_homepage'))

@bp.route('/welcome')
def welcome():
    return render_template('home/welcome.html')

#@bp.route('/features')
def features():
    return render_template('home/features.html')

web/templates/company/change_company_role.html
{% extends "layouts/L1.html" %}

{% block content %}
<div class='row'>
    <div class='col-sm-12'>
        <h3>{{ _('Change Company Roles') }}</h3>
  
    </div>

</div>
   
{% endblock %}

web/templates/company/company.html
{% extends "layouts/L1.html" %}

{% block center %}
<div class='row'>
    <div class='col-sm-12 col-md-5'>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

web/templates/company/company_rv.html
{% extends "layouts/L1.html" %}
{% import "components/company.html" as company_comps with context %}
{% import "components/misc.html" as misc_comps with context %}

{% block page_title %} {{ _('Company Information') }} {% endblock %}

{% block top_region_background %}
{% if current_user.is_authenticated and not company.is_public %}    
<div class='goto-my-home'>
    <a href='{{ url_for("home.default") }}'>{{ _('This page is currently set to be not visible to public. You can change the settings in Registration Information') }}
        <span class='fa fa-home'></span>
    </a>
</div>
{% endif %}
{{ company_comps.top_banner(company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.public_company_menu(company, current=current_tab) }}
{% endblock %}

{% block content %}
<div id='my-company-content' class='my-company-content'>
    {{ company_comps.render_company_section(company, current_tab=current_tab) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

{{ javascript_tag('company') | safe }}
<script>
  SUMO.company.my_company_page();
</script>

{% endblock %}

web/templates/company/create_company.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}

{% block page_title %} {{ _('Create Company Profile') }} {% endblock %}

{% block center %}
<div class='row'>
    <div class='col-12'>   
        <h3>{{ _('Create Company') }}</h3>
        <form id='company_create_form' method='POST'>
            
            {{ forms_macro.input('name', _('Company Name')) }}            
            {{ forms_macro.input('company_types', _('Company type')) }}            
            {{ forms_macro.select('country', _('Country'), items=geo.countries_as_tuples, default='US') }}          
            {{ forms_macro.input('location', _('Location')) }}           
            {{ forms_macro.input('website', _('Website')) }}            
            {{ forms_macro.textarea('description', _('Company Description'), richtext=False) }}
            {{ forms_macro.textarea('company_info', _('Additional Company Information')) }}   
            {{ forms_macro.input('phone', _('Phone')) }}            
            {{ forms_macro.input('fax', _('Fax')) }}           
            {{ forms_macro.input('email', _('Company Email (can be the same as your email)')) }}      
            {{ forms_macro.input('year_founded', _('Year Founded')) }}          
            {{ forms_macro.input('shipping_handling', _('Shipping Handled By')) }}      
            {{ forms_macro.select_from_list('company_size', _('Company Size'), items=constants.COMPANY_SIZES, default='') }}           
            {{ forms_macro.input('port', _('Ports')) }}                    
            {{ forms_macro.input('payment', _('Types of Accepted Payments')) }}        
            {{ forms_macro.submit_btn(text=_('Create')) }}
           
            
        </form>
                        
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ javascript_tag('company') | safe }}
<script>
    SUMO.company.handle_create_company_form();
</script>
{% endblock %}

web/templates/company/link_my_company.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}
{% import "components/company.html" as company_comps with context %}

{% block top_region %}

<h3>{% block page_title %} {{ _('Company Link') }} {% endblock %}</h3>

{% if company_old %}
<div class='row'>
    <div class='col-sm-12 col-md-6'>
        <h4 class='text-danger'>{{ _('You currently belong to the following organization') }}:</h4>
        <h5><a href="{{ url_for('company.company_page', pr_id=company_old.id) }}">{{ company_old.name }}</a>
        </h5>
        <p class='text-danger'>{{ _('You must leave your organization first before switching to a new company. You can leave by selecting leave company from your account page:') }}
            <a href="{{ url_for('account.my_account') }}">{{ _('Here') }}</a>
        </p>
    </div>
</div>


{% endif %}

{% if pending_request %}
<div class='row'>
    <div class='col-12'>
        <h5>{{ _('You have submitted link requests to') }}:</h5>
        {% for req in pending_request %}
            <div class='media company-item mb-3'>
                <div class='media-body'>
                    <h5 class='mt-0'>
                        <img style='width:35px; height:35px;'
                            src='{% if req.company.logo %}{{ req.company.logo }}{% else %}/static/img/company_default.png{% endif %}'>                
                        <a href="{{ url_for('company.company_page', pr_id=req.company.id) }}">{{ req.company.name }}</a>
                        <div class="link-box">
                            <div class='more-info-btn btn-info btn-sm' id='more-info-btn-{{ req.company.id }}' name='{{ req.company.id }}' data-toggle="modal" data-target="#company-modal-{{ req.company.id }}"
                            data-company_id='{{ req.company.id }}'>{{ _('More Info') }}</div>
                            <div class='btn-primary btn-sm'>
                                <a href="{{ url_for('company.verify_company') }}">
                                {{ _('Provide Verifying Document') }}
                                </a>
                            </div>

                        </div>

                    </h5> 
                    <div class='mt-2'>Trade60 ID: {{ req.company.id }}</div>
                </div>

            </div>
            <div class="modal fade" id="company-modal-{{ req.company.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{{ req.company.name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ company_comps.render_company_medium_info(req.company) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>
{% endif %}

<div class='row'>
    <div class='col-sm-12 col-md-6'>
    <h4>{{ _('Find Your Company') }}</h4>
    <form id='company_search_form' method='GET' name="company_search_form"  class='mb-3'>
        <div class="input-group">       
        <input class='form-control' placeholder="{{ _('Search by company name, keywords, or id') }}" type='text' id='search-input' name='search_term'>
        <div class="input-group-addon" id="search-company-btn"><i class="fa fa-search fa-3"></i></div>
        </div>
    </form>
    </div>
    <div class='col-sm-12 col-md-6'>
        <h5><b><i>{{ _('Cannot Find Your Company?') }}</i></b></h5>
        <a href='{{ url_for("company.create_company") }}'>{{ _('Create a new company profile') }}</a>
    </div> 
</div>
{% endblock %}

{% block content %}

<div class="row">
  <div class="col-sm-12 col-md-9">
      <div id='company-link-container'>
          {% if list_companies %}
          {% for company in list_companies %}
          <div class='media company-item mb-3'>
              <div class='media-body'>
                  <h5 class='mt-0'>
                      <img style='width:35px; height:35px;'
                          src='{% if company.media %}{{ company.media[0].thumbnail() }}{% else %}/static/img/company_default.png{% endif %}'>                
                      <a href="{{ url_for('company.company_page', pr_id=company.id) }}">{{ company.name }}</a>
                      <div class="link-box">
                            <div class='more-info-btn btn-info btn-sm' id='more-info-btn-{{ company.id }}' name='{{ company.id }}' data-toggle="modal" data-target="#company-modal-{{ company.id }}"
                            data-company_id='{{ company.id }}'>{{ _('More Info') }}</div>
                            
                            <div class='link-company-btn btn-update btn-sm' id='link-company-btn-{{ company.id }}' 
                            data-company_id='{{ company.id }}'>{{ _('Link to my Profile') }}</div>
                        </div>
                  </h5> 
                  <div>
                      {% for keyword in company.keywords[:10] %}
                      <span class='keyword'>{{ keyword }}</span>
                      {% endfor %}
                  </div>
                  <div class='mt-2'>Trade60 ID: {{ company.id }}</div>
                  <div class='mt-1'><i>
                      {% if company.description %} 
                      {{ company.description|striptags|strip_spaces|fmt_title(numchars=200)  }}
                      {% elif company.company_info %}
                      {{ company.company_info|striptags|strip_spaces|fmt_title(numchars=200) }}
                      {% endif %}
                    </i></div>
                  <div class='mt-1 mb-1'><b>{% if company.country %}{{ company.country|fmt_flag }}{% else %}
                        {{ company.location or "" }}
                        {% endif %}</b>
                  </div>
              </div>
          </div>

            <div class="modal fade" id="company-modal-{{ company.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{{ company.name }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ company_comps.render_company_medium_info(company) }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ _('Close') }}</button>
                    </div>
                    </div>
                </div>
            </div>
          {% endfor %}

          <div class='pages'>   
              {% set start = [1, current_page-5]|max %}
              {% set end = [start+5, num_pages]|min %}
              {% if start > 1 %}
              <span class='page-item' data-page='{{ current_page-1 }}'><i class='fa fa-chevron-left'></i></span>
              {% endif %}

              {% for i in range(start, end+1) %}
              <span class='page-item {% if current_page == i %}active{% endif %}' id='page-item-{{i}}' data-page='{{ i }}'>{{ i }}</span>
              {% endfor %}

              {% if end < num_pages %}
              <span class='page-item' data-page='{{ current_page+1 }}'><i class='fa fa-chevron-right'></i></span>
              {% endif %}
          </div>
          
          {% endif %}
      </div>
    
   </div>
 </div>
 
 

{% endblock %}

{% block scripts %}
{{ javascript_tag('company') | safe }}
<script>
  SUMO.company.link_company_page();
</script>

{% endblock %}

web/templates/company/my_company_al.html
{% extends "layouts/L1.html" %}
{% import "components/company.html" as company_comps with context %}

{% block center %}

  <ul class="nav nav-tabs" id='company-tabs'>
  
  <li class="nav-item active">
    <a class="nav-link active" data-toggle="tab" href="#main" role="tab">Summary</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#tab2" role="tab">Employee List</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#tab3" role="tab">Company Products</a>
  </li>
  
  </ul>


  <div class="tab-content">
      <div id="main" class="tab-pane in active" role="tabpanel">

        <div class='row'>
        <div class='col-sm-12 col-md-5'>
          {{ company_comps.my_company_al_html() }}
        </div>
        </div>
      
      </div>
      
      <div id="tab2" class="tab-pane" role="tabpanel">

      <div class='row'>
        <div class='col-sm-12 col-md-5'>
          {{ company_comps.company_employees_al_html() }}
        </div>
      </div>
      
      </div>
      
      <div id="tab3" class="tab-pane" role="tabpanel">
      <div class='row'>
        <div class='col-sm-12 col-md-5'>
            
            
        </div>
      </div>
      
      </div>

  </div>



</div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}

{{ javascript_tag('company') | safe }}
<script>
    SUMO.company.start_company_page();
</script>

{% endblock %}

web/templates/company/my_company_import_export.html
{% extends "layouts/L1.html" %}
{% import 'components/forms.html' as forms_macro with context %}
{% import "components/company.html" as company_comps with context %}

{% block page_title %} {{ _('Company Profile Import and Export') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.company_menu(company, current='import_export') }}
{% endblock %}

{% block center %}

<div>
    <h4>{{ _('Import Company Profile') }}</h4>
    <p>
        {{ _('Please download the following template, fill in the company information and upload the excel spreadsheet.') }}
        <br>
        <a href='{{ url_for("company.download_import_template") }}' target="_blank">
            {{ _('Download template') }} <i class='fa fa-download'></i>
        </a>
    </p>
    {% if import_docs %}
    <p>
        {{ _('We are currently processing these uploaded documents') }}:
        <ul>
            {% for doc in import_docs %}
            <li><i>{{ doc }}</i></li>
            {% endfor %}
        </ul>
    </p>
    {% endif %}
    <form method='POST' action='{{ url_for("company.import_profile") }}' 
        id='company_import_form' enctype="multipart/form-data">
        <input type='hidden' name='user_id' value='{{ current_user.id }}'>
        <input type='hidden' name='company_id' value='{{ company.id }}'>
        <div class='form-group'>
            <input type='file' name='import_doc' class='form-control'>
        </div>        
        <button type='submit' class='btn-import' id='import-btn'>{{ _('Import') }}</button>
    </form>
</div>
<br><br>
<div>
    <h4>{{ _('Export Company Profile') }}</h4>
    <form method='POST' action='{{ url_for("company.export_profile") }}' 
        id='company_export_form' enctype='multipart/form-data'>
        <input type='hidden' name='user_id' value='{{ current_user.id }}'>
        <input type='hidden' name='company_id' value='{{ company.id }}'>
        <div class='form-group'>
            <label for='export_format'>{{ _('Select an export format') }}</label>
            <select name='export_format' class='form-control'>
                <option value='xlsx'>Excel (.xlsx)</option>
            </select>            
        </div>        
        <button type='submit' class='btn-export' id='import-btn'>{{ _('Export') }}</button>
    </form>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}

{{ javascript_tag('company') | safe }}
<script>
  //SUMO.company.my_company_page();
</script>

{% endblock %}

web/templates/company/update_company_rv.html
{% extends "layouts/L1.html" %}

{% block center %}
<div class='row'>
    <div class='col-sm-12 col-md-5'>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}