web/forms/product.py
from .base import BaseValidator

product_create_form = BaseValidator('product_create_form', {

})
product_update_form = BaseValidator('product_update_form', {

})

web/views/product.py
from flask import Blueprint, render_template, redirect, url_for, request, abort, flash, send_file
from flask_login import login_required, current_user
from flask import current_app as app
from flask_babel import lazy_gettext
import ujson
from werkzeug import secure_filename
from io import BytesIO
import xlsxwriter
import string

from web import db, form_checker, role_manager, ds
from web.core import constants, geo
from role import role_constants

bp = Blueprint('product', __name__)

# Create a new product
@bp.route('/create-product')
@login_required
def create_product():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)

    if not user.company_id:
        return redirect(url_for('company.link_my_company'))

    # TBI: needs to check for Company or Organization or not enforce restriction
    if not role_manager.check_permission(current_user.id, 
                role_constants.OPERATION_PRODUCT, 
                role_constants.ACTION_CREATE):
        return abort(401)

    return render_template('product/create_product.html')

@bp.route('/company-products/<id_slug(model="company"):pr_id>')
def company_products(pr_id=None):

    company = db.company.get_by_id(pr_id)

    if not company:
        return abort(404)
    
    args = form_checker.process(request, 'product_list_form')        

    limit = 20

    keyword = args.pop('keyword', '')
    category = args.pop('category', '')    
    current_page = int(args.pop('current_page', 1))
    sorted_by = 'product.' + args.pop('sorted_by', 'name')    
    view = args.pop('view', 'grid')

    if category:
        num_pages, products, num_results = db.product.search(keyword=keyword, current_page=current_page, sorted_by=sorted_by,
            company_id=company.id, product_category_id=category)
    else:
        num_pages, products, num_results = db.product.search(keyword=keyword, current_page=current_page, sorted_by=sorted_by,
            company_id=company.id)

    categories = set((db.query(db.product_category.Model.id, db.product_category.Model.name)
                    .join(db.product.Model)
                    .filter(db.product.Model.company_id == company.id)).all())
    #categories = (db.query(db.product_category.Model.id, db.product_category.Model.name)
    #                .filter(db.product_category.Model.parent_category_id == None).all())    
    #categories = (db.query(db.product_category.Model.id, db.product_category.Model.name)
    #                .join(db.product.Model)).all()
                  #  .filter(db.product.Model.company_id == company.id)).all()
    

    return render_template('product/company_products.html', 
                            keyword=keyword,
                            category=category,
                            categories=categories,
                            company=company,
                            products=products,
                            current_page=current_page,
                            num_pages=num_pages,
                            view=view)

# All products belonging to current company associated with users
@bp.route('/manage-products')
@login_required
def manage_products():
    user = db.user.get_by_id(current_user.id)
    if not user.company_id:
        return redirect(url_for('company.link_my_company'))
        
    args = form_checker.process(request, 'product_list_form')
    
    if not role_manager.check_permission(current_user.id, 
                role_constants.OPERATION_PRODUCT, 
                role_constants.ACTION_VIEW):
        return abort(403)

    limit = 20
    keyword = args.pop('keyword', '')    
    current_page = int(args.pop('current_page', 1))
    sorted_by = 'product.' + args.pop('sorted_by', 'name')
    view = args.pop('view', 'grid')
    

    num_pages, products, num_results = db.product.search(keyword=keyword, current_page=current_page,
        sorted_by=sorted_by, company_id=user.company_id, search_hidden=True)

    return render_template('product/manage_products.html',
                            products=products,
                            current_page=current_page,
                            num_pages=num_pages,
                            keyword=keyword,
                            view=view)

# Specific product ID - using ajax retrieval
@bp.route('/product/<id_slug(model="product"):pr_id>')
def product_page(pr_id=None):
    product = db.product.get_by_id(pr_id)

    if not product:
        return abort(404)    

    is_updatable = False
    if current_user.is_authenticated:
        is_updatable = current_user.company_id == product.company.id

        user = db.user.get_by_id(current_user.id)
        if product.company_id != user.company_id and (not product.company.is_public):
            return abort(404)

    else:
        if not product.company.is_public:
            return abort(404)

    return render_template('product/product.html', product=product, is_updatable=is_updatable)
    
@bp.route('/update-product/<id_slug(model="product"):pr_id>')
@login_required
def update_product(pr_id):
    user = db.user.get_by_id(current_user.id)
    
     # Obtain product info
    product = db.product.get_by_id(pr_id)

    if not product:
        return abort(404)

    if (product.company_id != user.company_id) and (not product.company.is_public):
        return abort(404)

    
    # Only loads the page if the product is editable by current user
    if (product.company_id != user.company_id or 
            not role_manager.check_permission(current_user.id, 
                role_constants.OPERATION_PRODUCT, 
                role_constants.ACTION_UPDATE) ):
        # TBI: Add product_id to check permission parameter - separate permission for users
        return abort(403)
    
    view = request.args.get('view', None)

    return render_template('product/update_product.html', view=view, product=product)

@bp.route('/import-products', methods=['GET', 'POST'])
@login_required
def import_products():
    if not current_user.company_id:
        return abort(500)

    company = db.company.get_by_id(current_user.company_id)
    if not company:
        return abort(404)

    if request.method == 'POST':

        # Have permission to access page
        if not role_manager.check_permission(current_user.id, 
                role_constants.OPERATION_COMPANY, 
                role_constants.ACTION_UPDATE):
            flash(lazy_gettext('Sorry, you do not have permission to update company. Please contact your manager or us for more details'), 'danger')
            return redirect(url_for("product.import_products"))

        args = form_checker.process(request)

        if not request.files.get('import_doc', None):
            flash(lazy_gettext('Please upload a spreadsheet using our template'))
            return redirect(url_for("product.import_products"))

        folder = f'company/{company.id}/import_products_docs'
        import_doc = request.files['import_doc']
        if import_doc.filename.split('.')[-1] not in ['xlsx', 'xls']:
            flash(lazy_gettext('Invalid file type'), 'danger')
            return redirect(url_for("product.import_products"))

        obj_name, obj_url = ds.save_obj(folder, import_doc)

        flash(lazy_gettext('You have successfuly uploaded the spreadsheet! We are processing your company products and will keep you in the loop.'), 'success')
        return redirect(url_for("product.import_products"))

    folder = f'company/{company.id}/import_products_docs'
    import_docs = ds.list_objs(folder)

    return render_template('product/import_products.html', import_docs=import_docs)

spreadsheet_columns = [    
    ('name', 'Name', 25),
    ('description', 'Description', 50),
    ('product_category', 'Product Category', 15),
    ('capacity', 'Capacity', 15),
    ('min_order_quantity', 'Min Order Quantity', 15),
    ('unit_type', 'Unit Type', 15),
    ('payment_options', 'Payment Options', 15),
    ('price_range_min', 'Minimum Price', 15),
    ('price_range_max', 'Maximum Price', 15),
    ('packaging', 'Packaging', 15),
    ('port', 'Port', 15),
    ('payment_options', 'Payment Options', 15),
    ('processing_time', 'Processing Time', 15)
]

@bp.route('/import-products/download-template')
@login_required
def download_import_template():
    if not current_user.company_id:
        return abort(500)

    company = db.company.get_by_id(current_user.company_id)
    if not company:
        return abort(404)

    first_level_categories = db.product_category.get_first_levels(nameonly=True)
    file_name = f'{app.config["APP_NAME"]}_import_products_template.xlsx'

    output = BytesIO()
    workbook = xlsxwriter.Workbook(output)
    worksheet = workbook.add_worksheet()

    header_format = workbook.add_format({
        'border': 1,
        'bg_color': '#C6EFCE',
        'bold': True,
        'text_wrap': True,
        'valign': 'vcenter',
        'indent': 1,
    })

    worksheet.set_column('U:U', 15)    
    worksheet.write('U1', 'Product Categories', header_format)
    for idx, (cat,) in enumerate(first_level_categories):
        row_idx = idx + 2
        worksheet.write(f'U{row_idx}', cat)

    worksheet.set_column('V:V', 15) 
    worksheet.write('V1', 'Measure Units', header_format)
    for idx, mu in enumerate(constants.MEASURE_UNITS):
        row_idx = idx + 2
        worksheet.write(f'V{row_idx}', mu)

    alphabets = list(string.ascii_uppercase)

    for idx, items in enumerate(spreadsheet_columns):
        field,label,width = items
        col = alphabets[idx]
        worksheet.set_column(f'{col}:{col}', width)
        worksheet.write(f'{col}1', label, header_format)

        if field == 'product_category':
            worksheet.data_validation(f'{col}2:{col}1048576', 
                {'validate': 'list', 'source': f'=$U$2:$U${len(first_level_categories)}'})

        elif field == 'unit_type':
            worksheet.data_validation(f'{col}2:{col}1048576', 

web/templates/product/company_products.html
{% extends "layouts/L1.html" %}

{% import "components/company.html" as company_comps with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}
{% import "components/product.html" as product_comps with context %}

{% block page_title %} {{ _('Company Products') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.public_company_menu(company, current='products') }}
{% endblock %}

{% block center %}
<div class='breadcrumbs'>
    <span class='breadcrumb-link'><i><a href='{{ url_for("company.company_page", pr_id=company.id) }}'>{{ _('Home') }}</a></i></span>
    &nbsp;>>&nbsp;
    <span class='breadcrumb-link'><i><a href='{{ url_for("product.company_products", pr_id=company.id) }}'>{{ _('Company Products') }}</a></i></span>    
</div>

<br>

<div class='row'>
    <div class='col-sm-12 col-md-3'>
        <div class='company-products-categories-container'>
            <div class='mb-3' id='cp-search-box'>
                <div class="input-group">
                    <input id='cp-search-input' type="text" class="form-control" 
                        placeholder="{{ _('Find products') }}" value='{% if keyword %}{{ keyword }}{% endif %}'>
                    <span id='cp-search-btn' class="input-group-addon">
                        <i class='fa fa-search'></i>
                    </span>
                </div>        
            </div>

            <h5>{{ _('Product categories') }}</h5>
            <table class='table border-0 table-sm'>
            <tbody>
                <tr><td><a href='{{ url_for("product.company_products", pr_id=company.id) }}'>All</a></td></tr>
            {% for cat in categories %}
                <tr><td>       
                    <a href='{{ url_for("product.company_products", pr_id=company.id, category=cat[0]) }}'>{{ cat[1] }}</a>
                </td></tr>
            {% endfor %}
            </tbody>    
            </table>
        </div>
    </div>

    <div class='col-sm-12 col-md-9'>
        <div class='company-producst-container'>                    

            <div class='pm-select-view' id='pm-select-view'>
                <span id='pm-view-grid' data-view='grid' 
                    class='{% if view == "grid" %}active{% endif %}'>
                    <i class='fa fa-th-large'></i>
                </span>
                <span id='pm-view-list' data-view='list'
                    class='{% if view == "list" %}active{% endif %}'>
                    <i class='fa fa-list-ul mr-2'></i>
                </span>
            </div>

            <div class='row mt-4'>
                <div class='col-12'>
                    <div class='products-list-wrapper'>
                        {% if view == "list" %}
                            {{ product_comps.render_products_list(products) }}
                        {% else %}
                            {{ product_comps.render_products_grid(products) }}
                        {% endif %}
                        
                    </div>
                </div>
            </div>
                
            <div class='pages'>
                {% set start = [1, current_page-5]|max %}
                {% set end = [start+5, num_pages]|min %}
                {% if start > 1 %}
                <span class='page-item' data-page='{{ current_page-1 }}'><i class='fa fa-chevron-left'></i></span>
                {% endif %}

                {% for i in range(start, end+1) %}
                <span class='page-item {% if current_page == i %}active{% endif %}' id='page-item-{{i}}' data-page='{{ i }}'>{{ i }}</span>
                {% endfor %}

                {% if end < num_pages %}
                <span class='page-item' data-page='{{ current_page+1 }}'><i class='fa fa-chevron-right'></i></span>
                {% endif %}
            </div>
                    
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ javascript_tag('company_products_page') | safe }}
<script>
    SUMO.company_products_page.start_page();
</script>
{% endblock %}

web/templates/product/create_product.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}
{% import 'components/product.html' as product_comps with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}
{% import "components/company.html" as company_comps with context %}   

{% block page_title %} {{ _('Create a New Product') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(current_user.company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.company_menu(current_user.company, current='manage_products') }}
{% endblock %}


{% block content %}

{{ product_comps.topnav() }}

<div class='create-product-wrapper'>
    <form id='create-product-form' method='POST' enctype="multipart/form-data">
        <input type='hidden' name='company_id' value='{{ current_user.company_id }}'>
        {{ forms_macro.input('name', _('Product name')) }}
        {{ forms_macro.media_input('display_pic', _('Display Picture')) }}
        {{ forms_macro.input('keywords', _('Keywords')) }}        
        {{ product_cat_comps.select_category_cascade('create-product-select-category') }}
        {{ forms_macro.input('capacity', _('Capacity')) }}
        {{ forms_macro.input('min_order_quantity', _('Minimum order quantity')) }}
        {{ forms_macro.select_from_list('unit_type', _('Unit type'), items=constants.MEASURE_UNITS) }}
        {{ forms_macro.input_dual('price_range_min', 'price_range_max', _('Price range (in US Dollars)')) }}
        {{ forms_macro.checkboxes('payment_options', _('Payment options'), options=constants.PAYMENT_TYPES) }}
        {{ forms_macro.input('processing_time', _('Processing time')) }}
        {{ forms_macro.input('port', _('Port')) }}        
        {{ forms_macro.input('packaging', _('Packaging details')) }}        

        {{ forms_macro.textarea('description', _('Product Description')) }}        
        {{ forms_macro.media_input('media', _('Media')) }}

        {{ forms_macro.other_details() }}

        {{ forms_macro.submit_btn(text=_('Submit')) }}
        <a href='javascript:history.go(-1);'><span class='btn-cancel'>{{ _('Cancel') }}</span></a>
    </form>
            
</div>
{% endblock %}

{% block scripts %}
{{ javascript_tag('product') | safe }}
{{ super() }}
<script>
    SUMO.product.handle_create_product_form();
</script>
{% endblock %}


        

web/templates/product/export_products.html
{% extends "layouts/L1.html" %}

{% import 'components/product.html' as product_comps with context %}
{% import "components/company.html" as company_comps with context %}   

{% block page_title %} {{ _('Export Products') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(current_user.company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.company_menu(current_user.company, current='manage_products') }}
{% endblock %}


{% block content %}

{{ product_comps.topnav() }}
<div class='form-group'>
        <label for='export_format'>{{ _('Select an export format') }}</label>
        <select name='export_format' class='form-control'>
            <option value='xlsx'>Excel (.xlsx)</option>
        </select>            
    </div>
<div>
    <span class='btn-export'><a href="{{ url_for('api.product_export') }}">{{ _('Export Products') }}</a></span>    
</div>
{% endblock %}

{% block scripts %}
<script type="text/template">
</script>

<script>
</script>
{% endblock %}

web/templates/product/import_products.html
{% extends "layouts/L1.html" %}

{% import 'components/product.html' as product_comps with context %}
{% import "components/company.html" as company_comps with context %}   

{% block page_title %} {{ _('Import Products') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(current_user.company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.company_menu(current_user.company, current='manage_products') }}
{% endblock %}


{% block content %}

{{ product_comps.topnav() }}

<p>
    {{ _('Please download the following template, fill in your company products and upload the excel spreadsheet.') }}
    <br>
    <a href='{{ url_for("product.download_import_template") }}' target="_blank">
        {{ _('Download template') }} <i class='fa fa-download'></i>
    </a>
</p>
{% if import_docs %}
<p>
    {{ _('We are currently processing these uploaded documents') }}:
    <ul>
        {% for doc in import_docs %}
        <li><i>{{ doc }}</i></li>
        {% endfor %}
    </ul>
</p>
{% endif %}
<form method='POST' action='{{ url_for("product.import_products") }}' 
    id='products_import_form' enctype="multipart/form-data">
    <input type='hidden' name='user_id' value='{{ current_user.id }}'>
    <input type='hidden' name='company_id' value='{{ current_user.company_id }}'>
    <div class='form-group'>
        <input type='file' name='import_doc' class='form-control'>
    </div>        
    <button type='submit' class='btn-import' id='import-btn'>{{ _('Import') }}</button>
</form>

{% endblock %}

{% block scripts %}
<script type="text/template">
</script>

<script>
</script>
{% endblock %}

web/templates/product/manage_products.html
{% extends "layouts/L1.html" %}

{% import 'components/product.html' as product_comps with context %}
{% import "components/company.html" as company_comps with context %}    

{% block page_title %} {{ _('Manage Products') }} {% endblock %}

{% block top_region_background %}
{{ company_comps.top_banner(current_user.company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.company_menu(current_user.company, current='manage_products') }}
{% endblock %}

{% block content %}

{{ product_comps.topnav() }}

<div class='row medium-gutters'>
    <div class='col-sm-12 col-md-8 mb-5'>
        <h3 class='mb-2'>{{ _('All products') }}</h3>
        <div class='row'>
            <div class='col-12'>

                <div id='pm-search-box'>
                    <div class='float-left'>
                        <div class="input-group with-shadow">
                            <input id='pm-search-input' type="text" value="{% if keyword %}{{ keyword }}{% endif %}"
                                class="form-control" placeholder="{{ _('Find products') }}">
                            <span id='pm-search-btn' class="input-group-addon">
                                <i class='fa fa-search'></i>
                            </span>
                        </div>  

                    </div>

                    <div class='float-right pm-select-view' id='pm-select-view'>
                        <span id='pm-view-grid' data-view='grid' 
                            class='{% if view == "grid" %}active{% endif %}'>
                            <i class='fa fa-th-large'></i>
                        </span>
                        <span id='pm-view-list' data-view='list'
                            class='{% if view == "list" %}active{% endif %}'>
                            <i class='fa fa-list-ul mr-2'></i>
                        </span>
                    </div>
                </div>

            </div>            
        </div>    
        
        <div class='products-list-wrapper mt-3'>
        {% if view == "list" %}
            {{ product_comps.render_products_list(products, public=False) }}
        {% else %}
            {{ product_comps.render_products_grid(products, public=False) }}
        {% endif %}
        </div>            


        <div class='pages'>
            {% set start = [1, current_page-5]|max %}
            {% set end = [start+5, num_pages]|min %}
            {% if start > 1 %}
            <span class='page-item' data-page='{{ current_page-1 }}'><i class='fa fa-chevron-left'></i></span>
            {% endif %}

            {% for i in range(start, end+1) %}
            <span class='page-item {% if current_page == i %}active{% endif %}' id='page-item-{{i}}' data-page='{{ i }}'>{{ i }}</span>
            {% endfor %}

            {% if end < num_pages %}
            <span class='page-item' data-page='{{ current_page+1 }}'><i class='fa fa-chevron-right'></i></span>
            {% endif %}
        </div>               
        
    </div>


    <div class='col-sm-12 col-md-4'>
        <h5>{{ _('Customer Inquiries') }}</h5>        
        <div id='customer-inquiry-threads'>        
        </div>
    </div>

    <div class="modal" id="update-product-modal" tabindex="-1" role="dialog" aria-labelledby="pdate-product-modal-title" aria-hidden="true">
        <div class="modal-dialog  update-modal-content" role="document">
            <div class="modal-content" id='update-product-modal-content'>
            </div>
        </div>
    </div>    

</div>
{% endblock %}

{% block scripts %}
{{ javascript_tag('manage_products_page') | safe }}
<script>
    SUMO.manage_products_page.start_page();
</script>
{% endblock %}

web/templates/product/product.html
{% extends "layouts/L1.html" %}

{% import 'components/media.html' as media_comps with context %}            
{% import 'components/company.html' as company_comps with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}

{% block top_region_background %}
{{ company_comps.top_banner(product.company) }}
{% endblock %}

{% block top_region %}
{{ company_comps.public_company_menu(product.company, product=product, current='products') }}
{% endblock %}

{% block center %}
<div class='breadcrumbs'>
    <span class='breadcrumb-link'><i><a href='{{ url_for("company.company_page", pr_id=product.company.id) }}'>{{ _('Home') }}</a></i></span>
    &nbsp;>>&nbsp;
    <span class='breadcrumb-link'><i><a href='{{ url_for("product.company_products", pr_id=product.company.id) }}'>{{ _('Company Products') }}</a></i></span>
    &nbsp;>>&nbsp;
    <span class='breadcrumb-link'><i><a href='{{ url_for("product.product_page", pr_id=product.id) }}'>{{ product.name | fmt_title }}</a></i></span>
</div>

<br>

<div class='row'>
    <div class='col-sm-12 col-md-9'>
        <div class='product-content-wrapper'>
            <h4>{% block page_title %} {{ product.name }} {% endblock %}</h4>
            <br>
            <div class='row medium-gutters'>
                <div class='col-12 col-sm-4'>
                    <div class='product-display-pic'>
                        <img src="{{ product.display_pic or '/static/img/product_default.png' }}" />
                    </div>                    
                    <a class='btn-block btn-contact' href='{{ url_for("messages.product_inquiry_thread_page", product_id=product.id) }}'><i class='fa fa-comments'></i>&nbsp;{{ _('Inquire Now') }}</a>                    
                    <button class='btn-block btn-light' onclick='window.add_to_basket("{{ product.id }}")'><i class='fa fa-cart-plus'></i>&nbsp;{{ _('Add to Basket') }}</button>
                    <br>
                </div>
                <div class='col-12 col-sm-8'>
                    <table class='details-table'>
                        <tbody>
                            <tr>
                                <th>{{ _('Keywords') }}</th>
                                <td>
                                    {% if product.keywords %}        
                                    {% for kw in product.keywords %}
                                    <span class='keyword'>{{ kw }}</span>
                                    {% endfor %}
                                    {% else %}
                                    {{ _('Not Available') }}
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th>{{ _('Product category') }}</th>
                                <td>{{ product_cat_comps.render_product_cat_breadcrumb(product.product_category.path) }}</td>
                            </tr>
                            <tr>
                                <th>{{ _('Capacity') }}</th>
                                <td>{{ product.capacity or _("Not Available") }}</td>
                            </tr>            
                            <tr>
                                <th>{{ _('Minimum order quantity') }}</th>
                                <td>{{ product.min_order_quantity or _("Not Available") }}</td>
                            </tr>
                            <tr>
                                <th>{{ _('Price range') }}</th>
                                <td>{{ product.price_range or _("Not Available") }}</td>
                            </tr>        
                            
                        </tbody>
                    </table>    
                </div>            
            </div>

            <br>
            <h4>Product Information</h4>
            <div class='scrollable'>
            <table class='details-table'>
                <tbody>
                    <tr>
                        <th>{{ _('Payment options') }}</th>
                        <td>{% if product.payment_options %}{{ product.payment_options | fmt_list }}{% else %}{{ _("Not Available") }}{% endif %}</td>
                    </tr>
                    <tr>
                        <th>{{ _('Packaging') }}</th>
                        <td>{{ product.packaging or _("Not Available") }}</td>
                    </tr>
                    <tr>
                        <th>{{ _('Port') }}</th>
                        <td>{{ product.port or _("Not Available") }} </td>
                    </tr>
                    <tr>
                        <th>{{ _('Processing time') }}</th>
                        <td>{{ product.processing_time or _("Not Available") }}</td>
                    </tr>
                    {% if product.other_details %}
                    {% for key,val in product.other_details.items() %}
                    <tr>
                        <th>{{ key }}</th>
                        <td>{{ val }}</td>
                    </tr>
                    {% endfor %}
                    {% endif %}                   
                    
                </tbody>
            </table>
            </div>

            <div class='scrollable'>
                {% if product.description %}{{ product.description | safe }}{% endif %}
            </div>

            {{ media_comps.render_media_grid(product.media_list)  }}

            {% if is_updatable %}
            <a href='{{ url_for("product.update_product", pr_id=product.id) }}'>
                <span class='btn-update'>{{ _('Update') }}</span>
            </a>    
            {% endif %}
        </div>
    </div>
    <div class='col-sm-12 col-md-3'>
        {{ company_comps.render_company_short_info(product.company) }}
    </div>
</div>
{% endblock %}

{% block scripts %}

{{ javascript_tag('product') | safe }}

<script>    
    load_media_grid_lightbox('#media-grid');
</script>
{% endblock %}