web/forms/rfq.py
from .base import BaseValidator

rfq_get_form = BaseValidator('rfq_get_form', {
})

rfq_create_form = BaseValidator('rfq_create_form', {
})

rfq_update_form = BaseValidator('rfq_update_form', {

})

web/views/account.py
from flask import render_template, Blueprint, redirect, url_for, abort, request, session, flash
from flask import current_app as app
from flask_login import login_required, current_user
from flask_mail import Message
from flask_babel import lazy_gettext
from web import db, form_checker
from web.core import utils

bp = Blueprint('account', __name__)

@bp.route('/my-account')
@login_required
def my_account():
    return render_template('account/my_account.html')

@bp.route('/change-password')
@login_required
def change_password():
    return render_template('account/change_password.html')

@bp.route('/my-account/settings')
@login_required
def settings():
    blocked_users = None
    num_pages = 0
    #limit = 20
    num_results = 0

    if current_user.privacy_settings:
        blocked_ids = current_user.privacy_settings['privacy_blocked_users']
        num_pages, users, num_results = db.user.search_list_id(blocked_ids)
        blocked_users = [ u.to_blocked_dict() for u in users if u.is_visible() ]

    return render_template('account/settings.html', 
        num_pages=num_pages, 
        num_results=num_results, 
        blocked_users=blocked_users)

@bp.route('/my-contacts')
@login_required
def my_contacts():
    user = db.user.get_by_id(current_user.id)
    colleagues = []
    biz_contacts = []
    if user.company_id:
        colleagues = [u for u in user.company.users if u.id != user.id]
    
    biz_contacts = db.thread.get_user_contacts(user)
    biz_contacts = [u for u in biz_contacts if u not in colleagues]

    return render_template('account/my_contacts.html',
        colleagues=colleagues, biz_contacts=biz_contacts
    )

@bp.route('/account/<pr_id>')
def account_page(pr_id):
    user = db.user.get_by_id(pr_id)

    if not user:
        return abort(404)

    return render_template('account/account.html', user=user)

@bp.route('/invitation')
def invite():
    ref_user_id = request.args.get('uid', None)
    ref_company_id = request.args.get('cid', None)

    if current_user.is_authenticated:
        user = db.user.get_by_id(current_user.get_id())

        return redirect(url_for("company.link_my_company", uid=ref_user_id, cid=ref_company_id))
    else:
        return redirect(url_for("auth.register", uid=ref_user_id, cid=ref_company_id))

@bp.route('/my-basket', methods=['GET', 'POST'])
@login_required
def my_basket():
    pids = session.get('BASKET_PRODUCTS', None)
    products = []
    
    if pids:
        products = db.product.get_by_ids(list(pids))

    if request.method == 'GET':
        return render_template('account/my_basket.html', products=products)


    if request.method == 'POST':
        # POST FORM
        args = form_checker.process(request)
        text = args.get('text', None)

        if not text:
            flash(lazy_gettext('You have to fill in the message form.'), 'danger')
            return render_template('account/my_basket.html', products=products)

        num_products = len(products)

        if not num_products:
            flash(lazy_gettext('Your basket is empty'))
            return render_template('account/my_basket.html', products=products)

        threads = db.thread.get_or_create_bulk_product_inquiry_threads(current_user.id, products, text=text)
        
        products = session['BASKET_PRODUCTS'] = set()
        
        #flash(lazy_gettext(f'Successfully sent {num_products} product inquiries to sellers.'), 'success')
        flash(lazy_gettext(u'Successfully sent {} product inquiries to sellers.').format(num_products), 'success')

        return render_template('account/my_basket.html', products=list(products))

web/views/quote.py
from flask import Blueprint, render_template, abort, redirect, url_for, request
from flask_login import current_user, login_required

from web import db, form_checker, role_manager

bp = Blueprint('quote', __name__)

@bp.route('/create-quote')
@login_required
def create_quote():
    rfq_id = request.args.get('rfq_id', None)
    if not rfq_id:
        return render_template('/quote/create_quote_no_rfq.html')

    rfq = db.rfq.get_by_id(rfq_id)
    if not rfq:
        return abort(404)

    if rfq.buyer_id == current_user.id:
        return abort(401)
    
    user = db.user.get_by_id(current_user.id)
    if not user.company_id:
        return redirect(url_for('company.link_my_company'))
    
    products = db.product.get_by_company_id(user.company_id)
    
    view = request.args.get('view', None)
    
    return render_template('/quote/create_quote.html', view=view, rfq=rfq, products=products)

@bp.route('/quote/<id_slug(model="quote",attr="title"):pr_id>')
@login_required
def quote_page(pr_id):
    quote = db.quote.get_by_id(pr_id)
    if not quote:
        return abort(404)

    is_owner = current_user.id == quote.seller_id

    return render_template('quote/quote.html', quote=quote, is_owner=is_owner)

@bp.route('/update-quote/<id_slug(model="quote",attr="title"):pr_id>')
@login_required
def update_quote(pr_id):
    quote = db.quote.get_by_id(pr_id)
    if not quote:
        return abort(404)

    if current_user.id != quote.seller_id:
        return abort(401)

    user = db.user.get_by_id(current_user.id)
    if not user.company_id:
        return redirect(url_for('company.link_my_company'))
    
    products = db.product.get_by_company_id(user.company_id)

    return render_template('/quote/update_quote.html', quote=quote, products=products)

@bp.route('/manage-quotes')
@login_required
def manage_quotes():
    quotes = db.quote.get_by_seller_id(current_user.id)
    return render_template('/quote/manage_quotes.html', quotes=quotes)

web/views/rfq.py
from flask import Blueprint, render_template, abort, request
from flask_login import current_user, login_required

from web import db, form_checker, role_manager

bp = Blueprint('rfq', __name__)

@bp.route('/create-rfq', methods=['GET'])
@login_required
def create_rfq():
    args = form_checker.process(request)
    product = args.get('product', '')    
    quantity = ''
    if args.get('quantity', None):
        quantity += f'{args.get("quantity")} '
    
    if args.get('unit', None):
        quantity += args.get('unit')
    
    return render_template('rfq/create_rfq.html', product=product, quantity=quantity)

@bp.route('/manage-rfqs')
@login_required
def manage_rfqs():
    rfqs = db.rfq.get_by_buyer_id(current_user.id)    
    return render_template('/rfq/manage_rfqs.html', rfqs=rfqs)

@bp.route('/rfq/<id_slug(model="rfq",attr="product"):pr_id>')
@login_required
def rfq_page(pr_id):
    rfq = db.rfq.get_by_id(pr_id)

    if not rfq:
        return abort(404)
    
    is_owner = False
    quotes = db.quote.get_by_rfq_id(rfq.id)

    if current_user.is_authenticated and rfq.buyer_id == current_user.id:
        is_owner = True
    else:
        quotes = [ x for x in quotes if x.seller_id == current_user.id ]
    
    return render_template('/rfq/rfq.html', 
                            rfq=rfq, 
                            quotes=quotes,
                            is_owner=is_owner)

@bp.route('/update-rfq/<id_slug(model="rfq",attr="product"):pr_id>')
@login_required
def update_rfq(pr_id):
    rfq = db.rfq.get_by_id(pr_id)

    if not rfq:
        return abort(404)

    if current_user.id != rfq.buyer_id:
        return abort(403)
    
    return render_template('/rfq/update_rfq.html', rfq=rfq)

@bp.route('/sourcing')
def sourcing():

    args = form_checker.process(request, 'search_rfq')
    keyword = args.pop('keyword', '')
    category = args.pop('category', None)
    limit = int(args.pop('limit', 20))
    current_page = int(args.pop('current_page', 1))    

    num_pages, rfqs = db.rfq.search(keyword=keyword, category=category, 
                                    limit=limit, current_page=current_page)

    categories = [('', 'All')] + (db.query(db.product_category.Model.id, db.product_category.Model.name)
                    .filter(db.product_category.Model.parent_category_id == None).all())    

    return render_template('/rfq/sourcing.html',
                            keyword=keyword,
                            category=category,
                            categories=categories,
                            current_page=current_page,
                            num_pages=num_pages,
                            rfqs=rfqs)

web/templates/rfq/create_rfq.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}

{% block page_title %} {{ _('Create a New RFQ') }} {% endblock %}

{% block content %}
<div id='create-rfq-form-wrapper'>
    <h3>{{ _('Create a new Request for Quotation (RFQ)') }}</h3>    
    <form id='create-rfq-form' method='POST' enctype="multipart/form-data">
        {{ forms_macro.input('product', _('Product'), value=product) }}
        {{ product_cat_comps.select_category_cascade('create-rfq-select-category') }}
        {{ forms_macro.input('quantity', _('Quantity'), value=quantity) }}
        {{ forms_macro.textarea('content', _('Content')) }}
        {{ forms_macro.input('keywords', _('Keywords (comma separated)')) }}
        {{ forms_macro.checkbox('is_public', _('Is public?'), checked=True, type='checkbox') }}
        {{ forms_macro.media_input('media', _('Media'), multiple=True) }}
        {{ forms_macro.other_details() }}

        {{ forms_macro.submit_btn(text=_('Submit')) }}
        <a href='javascript:history.go(-1);'><span class='btn-cancel'>{{ _('Cancel') }}</span></a>
    </form>
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
{{ javascript_tag('rfq') | safe }}
<script>
    SUMO.rfq.handle_create_rfq_form();
</script>
{% endblock %}

web/templates/rfq/create_rfq_no_login.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}

{% block page_title %} {{ _('Create a New RFQ') }} {% endblock %}

{% block content %}
<div id='create-rfq-form-wrapper'>
    <h3>{{ _('Create a new RFQ') }}</h3>
    <form id='create-rfq-form' method='POST' enctype="multipart/form-data">
        {{ forms_macro.input('product', _('Product')) }}
        {{ product_cat_comps.select_category_cascade('create-rfq-select-category') }}
        {{ forms_macro.input('quantity', _('Quantity')) }}
        {{ forms_macro.textarea('content', _('Content')) }}
        {{ forms_macro.input('keywords', _('Keywords (comma separated))') }}
        {{ forms_macro.checkbox('is_public', _('Is public?'), checked=True, type='checkbox') }}
        {{ forms_macro.media_input('media', _('Media'), multiple=True) }}
        {{ forms_macro.other_details() }}

        {{ forms_macro.submit_btn(text=_('Submit')) }}
        <a href='javascript:history.go(-1);'><span class='btn-cancel'>{{ _('Cancel') }}</span></a>
    </form>
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
{{ javascript_tag('rfq') | safe }}
<script>
    SUMO.rfq.handle_create_rfq_form();
</script>
{% endblock %}

web/templates/rfq/manage_rfqs.html
{% extends "layouts/L1.html" %}

{% import "components/account.html" as account_comps with context %}
{% import "components/rfq.html" as rfq_comps with context %}

{% block top_region %}
<h3 class='account-top-info'>{{ _("Manage My RFQs") }}</h3>
{% endblock %}

{% block page_title %} {{ _('Manage RFQs') }} {% endblock %}

{% block top_region_background %}
{{ account_comps.top_banner(current_user) }}
{% endblock %}

{% block content %}

<div class='row medium-gutters'>

    <div class='col-sm-12 order-md-9 col-md-3'>

        <div class='create-rfq-btn mb-3'>
            <a href='{{ url_for("rfq.create_rfq") }}' class='btn-new-rfq'>{{ _('Create an RFQ') }}</a>
        </div>
        
    </div>

    <div class='col-sm-12 col-md-9'>

        <div class='rfqs-list-wrapper'>
            {{ rfq_comps.render_rfqs(rfqs) }}
        </div>
         
    </div>
    
</div>
{% endblock %}

web/templates/rfq/rfq.html
{% extends "layouts/L1.html" %}
{% import "components/quote.html" as quote_comps with context %}
{% import 'components/media.html' as media_comps with context %}
{% import 'components/account.html' as account_comps with context %}

{% block page_title %} {{ _('RFQ') }} | {{ rfq.product }} {% endblock %}

{% block top_region_background %}
<div class='rfq-top-background'
    style='background-image: url("{{ rfq.product_category.path[0].name|company_banner }}");
    background-size: cover; background-position:center;'>
    <div class='rfq-top-background-overlay'></div>
</div>
{% endblock %}

{% block top_region %}
<h3 class='rfq-top-info'>RFQ | {{ rfq.product }}
    <a class='btn-contact'
        href='{{ url_for("messages.rfq_thread_page", rfq_id=rfq.id) }}'>{{ _('Contact Buyer') }}</a>
</h3>
{% endblock %}

{% block content %}
<div class='row rfq-page-wrapper'>
    <div class='col-sm-12 col-md-9'>
        <div class='rfq-page-category mb-2 category-path'><i>{{ rfq.product_category.path_as_str }}</i></div>
        <div class='rfq-page-keywords'>
            {% for keyword in rfq.keywords %}
            <span class='keyword'>{{ keyword }}</span>
            {% endfor %}
        </div>
        
        <table class='details-table'>
            <tbody>
                <tr>
                    <th>{{ _('Status') }}</th>
                    <td>
                        {% if rfq.is_expired %}
                        <span class='rfq-status rfq-expired'>{{ _('Expired') }}</span>
                        {% else %}
                        <span class='rfq-status rfq-active'>{{ _('Active') }}</span>
                        {% endif %}
                    </td>                    
                </tr>
                <tr>
                    <th>{{ _('Create time') }}</th>
                    <td>{{ rfq.create_time }}</td>
                </tr>
                <tr>
                    <th>{{ _('End time') }}</th>
                    <td>{{ rfq.end_time }}</td>
                </tr>                
                <tr>
                    <th>{{ _('Time left') }}</th>
                    <td><span class='time-left'>{{ rfq.time_left_str }}</span></td>
                </tr>
                <tr>
                    <th>{{ _('Quotes left') }}</th>
                    <td><span class='quotes-left'>{{ rfq.quotes_left }}</span></td>
                </tr>
                <tr>
                    <th>{{ _('Buyer') }}</th>
                    <td><a href='{{ url_for("account.account_page", pr_id=rfq.buyer.id) }}'>{{ rfq.buyer.name }}</a></td>
                </tr>
                <tr>
                    <th>{{ _('Company') }}</th>
                    <td>
                    {% if rfq.buyer.company_id %}
                        <a href='{{ url_for("company.company_page", pr_id=rfq.buyer.company.id) }}'>{{ rfq.buyer.company.name }}
                        </a>
                    {% else %}
                        {{ rfq.buyer.company_name }}
                    {% endif %}
                    </td>
                </tr>                
                <tr>
                    <th>{{ _('Quantity') }}</th>
                    <td>{{ rfq.quantity }}</td>
                </tr>
                {% if rfq.other_details %}
                {% for key,val in rfq.other_details.items() %}
                <tr>
                    <th>{{ key }}</th>
                    <td>{{ val }}</td>
                </tr>                
                {% endfor %}
                {% endif %}
                <tr>
                    <td colspan=2>
                        {{ media_comps.render_media_grid(rfq.media_list)  }}
                    </td>
                </tr>                             
                <tr>
                    <td colspan=2>{{ rfq.content|safe }}</td>
                </tr>
            </tbody>
        </table>
        
        <div>
        {% if is_owner %}
            <a class='btn-update mb-3' href='{{ url_for("rfq.update_rfq", pr_id=rfq.id) }}'>{{ _('Update') }}</a>            
            <br>
            <h5>{{ _('All quotes') }}</h5>
            {{ quote_comps.quotes_list(quotes) }}
        {% else %}            
            <h5>{{ _('My quotes') }}
                {% if not rfq.is_expired %}
                <a class='btn-new-quote' href='{{ url_for("quote.create_quote", rfq_id=rfq.id) }}'>
                    {{ _('New Quote') }}
                </a>
                {% endif %}
            </h5>
            {{ quote_comps.quotes_list(quotes) }}        
        {% endif %}
        </div>

    </div>
    <div class='col-sm-12 col-md-3'>
        {{ account_comps.render_account_short_info(rfq.buyer, title=_('Buyer profile')) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    load_media_grid_lightbox('#media-grid');
</script>
{% endblock %}

web/templates/rfq/sourcing.html
{% extends "layouts/L1.html" %}

{% import "components/rfq.html" as rfq_comps with context %}

{% block page_title %} {{ _('Sourcing') }} {% endblock %}

{% block top_region_background %}
<div class='sourcing-top-background'>
</div>
{% endblock %}

{% block top_region %}
<div class='row'>
    <div class='col-12'>
        <div class='sourcing-search-container'>
            <h3 class='sourcing-title'>{{ _('Request for Quotation') }}</h3>
            <div class='sourcing-search-box'>
                <div class='input-group with-shadow'>
                    <span class='input-group-addon' id='categories-btn' style='cursor: pointer;'>
                        <i class='fa fa-list-ul'></i>&nbsp;&nbsp;
                        <i class='fa fa-caret-down'></i>
                    </span>
                    <input class='form-control' type='text' name='search' value='{% if keyword %}{{ keyword }}{% endif %}'
                            id='search-input' placeholder="{{ _('Type a keyword to search RFQs') }}">
                    <span class='input-group-addon' id='search-btn'><i class='fa fa-search fa-3'></i></span>
                </div>
                <div style='display:none;' class='categories-container' id='categories-container'>
                {{ render_categories(categories) }}
                </div>                    
            </div>
            
            <div class='sourcing-my-searches-btn'>
                <span class='btn btn-dark ml-2 '>{{ _('My searches') }}
                    <i class='fa fa-caret-down'></i>
                </span>
            </div>       
        </div>   

    </div>
</div>
{% endblock %}

{% block content %}
<div class='sourcing-wrapper'>

    <div class='sourcing-main row medium-gutters'>

        <div class='col-sm-12 order-md-9 col-md-3'>

            <div class='create-rfq-btn mb-3'>
                <a href='{{ url_for("rfq.create_rfq") }}' class='btn-new-rfq'>{{ _('Create an RFQ') }}</a>
            </div>
            
        </div>

        <div class='col-sm-12 col-md-9'>
            <div id='rfqs-list-wrapper'>
            {{ rfq_comps.render_rfqs(rfqs) }}
            </div>

            <div class='pages'>
                {% set start = [1, current_page-5]|max %}
                {% set end = [start+5, num_pages]|min %}
                {% if start > 1 %}
                <span class='page-item' data-page='{{ current_page-1 }}'><i class='fa fa-chevron-left'></i></span>
                {% endif %}

                {% for i in range(start, end+1) %}
                <span class='page-item {% if current_page == i %}active{% endif %}' id='page-item-{{i}}' data-page='{{ i }}'>{{ i }}</span>
                {% endfor %}

                {% if end < num_pages %}
                <span class='page-item' data-page='{{ current_page+1 }}'><i class='fa fa-chevron-right'></i></span>
                {% endif %}
            </div>
            
            <br>
        </div>  

    </div>

</div>
{% endblock %}

{% macro render_categories(categories) %}
<div class='row'>
    {% for id,name in categories %}
    <div class='category-item col-sm-12 col-md-3 {% if (not id and not category) or category|int == id %}active{% endif %}' 
        data-category='{{ id }}'>{{ name }}</div>
    {% endfor %}
</div>
{% endmacro %}


{% block scripts %}
{{ super() }}
{{ javascript_tag('sourcing_page') | safe }}
<script>
    SUMO.sourcing_page.start_page();
</script>
{% endblock %}

web/templates/rfq/update_rfq.html
{% extends "layouts/L1.html" %}

{% import 'components/forms.html' as forms_macro with context %}
{% import 'components/product_category.html' as product_cat_comps with context %}

{% block page_title %} {{ _('Update RFQ ') }} | {{ rfq.product }} {% endblock %}

{% block content %}
<div id='update-rfq-form-wrapper'>
    <h3>{{ _('RFQ') }} | {{ rfq.product }}</h3>
    <form id='update-rfq-form' method='POST' enctype="multipart/form-data">
        <input type='hidden' name='rfq_id' value='{{ rfq.id }}'>
        {{ forms_macro.input('product', _('Product'), value=rfq.product) }}        
        {{ product_cat_comps.select_category_cascade('update-rfq-select-category', 
            value=rfq.product_category.id, 
            selected_category=rfq.product_category.path_as_str) }}
        {{ forms_macro.input('quantity', _('Quantity'), value=rfq.quantity) }}
        {{ forms_macro.textarea('content', _('Content'), value=rfq.content) }}
        {{ forms_macro.input('keywords', _('Keywords (comma separated)'), value=', '.join(rfq.keywords)) }}
        {{ forms_macro.checkbox('is_public', _('Is public?'), checked=rfq.is_public, type='checkbox') }}
        {{ forms_macro.media_input('media', _('Add media'), items=rfq.media_list,
            multiple=True, datatype='rfq')}}
        {{ forms_macro.other_details(values=rfq.other_details) }}

        {{ forms_macro.submit_btn(text=_('Submit')) }}
        
        {# forms_macro.action_btn(
            url_for('api.rfq_delete', rfq_id=rfq.id),
            url_for('rfq.manage_rfqs'),
            confirm_text=_('Are you sure to delete this RFQ?'),
            text=_('Delete'),
            name='delete-rfq',
            cls='btn-danger') #}            
        <a href='javascript:history.go(-1);' class='btn-cancel'>{{ _('Cancel') }}</a>        
    </form>
</div>
{% endblock %}


{% block scripts %}
{{ super() }}
{{ javascript_tag('rfq') | safe }}
<script>
    SUMO.rfq.handle_update_rfq_form();
</script>
{% endblock %}