web/views/account.py
from flask import render_template, Blueprint, redirect, url_for, abort, request, session, flash
from flask import current_app as app
from flask_login import login_required, current_user
from flask_mail import Message
from flask_babel import lazy_gettext
from web import db, form_checker
from web.core import utils

bp = Blueprint('account', __name__)

@bp.route('/my-account')
@login_required
def my_account():
    return render_template('account/my_account.html')

@bp.route('/change-password')
@login_required
def change_password():
    return render_template('account/change_password.html')

@bp.route('/my-account/settings')
@login_required
def settings():
    blocked_users = None
    num_pages = 0
    #limit = 20
    num_results = 0

    if current_user.privacy_settings:
        blocked_ids = current_user.privacy_settings['privacy_blocked_users']
        num_pages, users, num_results = db.user.search_list_id(blocked_ids)
        blocked_users = [ u.to_blocked_dict() for u in users if u.is_visible() ]

    return render_template('account/settings.html', 
        num_pages=num_pages, 
        num_results=num_results, 
        blocked_users=blocked_users)

@bp.route('/my-contacts')
@login_required
def my_contacts():
    user = db.user.get_by_id(current_user.id)
    colleagues = []
    biz_contacts = []
    if user.company_id:
        colleagues = [u for u in user.company.users if u.id != user.id]
    
    biz_contacts = db.thread.get_user_contacts(user)
    biz_contacts = [u for u in biz_contacts if u not in colleagues]

    return render_template('account/my_contacts.html',
        colleagues=colleagues, biz_contacts=biz_contacts
    )

@bp.route('/account/<pr_id>')
def account_page(pr_id):
    user = db.user.get_by_id(pr_id)

    if not user:
        return abort(404)

    return render_template('account/account.html', user=user)

@bp.route('/invitation')
def invite():
    ref_user_id = request.args.get('uid', None)
    ref_company_id = request.args.get('cid', None)

    if current_user.is_authenticated:
        user = db.user.get_by_id(current_user.get_id())

        return redirect(url_for("company.link_my_company", uid=ref_user_id, cid=ref_company_id))
    else:
        return redirect(url_for("auth.register", uid=ref_user_id, cid=ref_company_id))

@bp.route('/my-basket', methods=['GET', 'POST'])
@login_required
def my_basket():
    pids = session.get('BASKET_PRODUCTS', None)
    products = []
    
    if pids:
        products = db.product.get_by_ids(list(pids))

    if request.method == 'GET':
        return render_template('account/my_basket.html', products=products)


    if request.method == 'POST':
        # POST FORM
        args = form_checker.process(request)
        text = args.get('text', None)

        if not text:
            flash(lazy_gettext('You have to fill in the message form.'), 'danger')
            return render_template('account/my_basket.html', products=products)

        num_products = len(products)

        if not num_products:
            flash(lazy_gettext('Your basket is empty'))
            return render_template('account/my_basket.html', products=products)

        threads = db.thread.get_or_create_bulk_product_inquiry_threads(current_user.id, products, text=text)
        
        products = session['BASKET_PRODUCTS'] = set()
        
        #flash(lazy_gettext(f'Successfully sent {num_products} product inquiries to sellers.'), 'success')
        flash(lazy_gettext(u'Successfully sent {} product inquiries to sellers.').format(num_products), 'success')

        return render_template('account/my_basket.html', products=list(products))

web/views/company.py
from flask import Blueprint, render_template, request, abort, views, redirect, url_for, abort, flash, send_file
from flask_login import login_required, current_user, login_user
from werkzeug import secure_filename
from io import BytesIO
import xlsxwriter
from flask import current_app as app
from flask_babel import lazy_gettext

import database.models as models
from web import db, form_checker, role_manager, ds
from web.core import constants, geo
import database.enums as db_enums
from role import role_constants

bp = Blueprint('company', __name__)

# Disabled - not allowing creating new company at the moment
# HShould be andled instead by views in register

@bp.route('/create-company')
@login_required
def create_company():
    # Check if user already has a linked company
    #if current_user.is_authenticated:  # checked by decorator
    user = db.user.get_by_id(current_user.get_id())
    if user.company_id: # Company already associated with user
        # user.company_name is used for verification purpose
        return redirect(url_for('company.my_company'))
    
    return render_template('company/create_company.html')

# updating current company associated with user
@bp.route('/my-company/update')
@login_required
def update_company_rv():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))

    # Have permission to access page
    if not role_manager.check_permission(user_id, 
                role_constants.OPERATION_COMPANY, 
                role_constants.ACTION_UPDATE):
        return redirect(url_for('company.my_company'))
    
    company_info = user.company.to_dict()

    return render_template('company/update_company_rv.html', my_company=company_info)

# Company associated to the current user
@bp.route('/my-company')
@login_required
def my_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))
        
    # Obtaining company information
    company = user.company
    #company_info = company.to_dict()
    
    # Checking for editing permission
    company_is_editable = False

    if role_manager.check_permission(user_id, 
                role_constants.OPERATION_COMPANY, 
                role_constants.ACTION_UPDATE):
        company_is_editable = True
   
    # Obtaining employee lists
    #employees = company.users  
    #employee_list = [ employee.to_public_dict() for employee in employees ]    

    first_level_categories = db.product_category.get_first_levels()
  
    return render_template('company/my_company_rv.html', 
        company=company, 
        company_is_editable=company_is_editable,
        datatype="company",
        first_level_categories=first_level_categories)
        #, employee_list=employee_list)


# Specific company by ID with full rendering in template - grouped for public and internal views
@bp.route('/company/<id_slug(model="company"):pr_id>')
def company_page(pr_id):
    is_company_emp = False
    company = db.company.get_by_id(pr_id)
    if not company:
        return abort(404)

    if current_user.is_authenticated:
        user_id = current_user.get_id()
        user = db.user.get_by_id(user_id)
        if user.company_id == company.id:
            is_company_emp = True
        
    if (not company.is_public) and (not is_company_emp):
        return abort(404)

    args = form_checker.process(request)
    current_tab = args.get('tab', 'home')
    
    return render_template('company/company_rv.html', 
        company=company, current_tab=current_tab)


@bp.route('/change-company-role', methods=['GET'])
@login_required
def change_company_role():
    return render_template('company/change_company_role.html')


@bp.route('/link-my-company')
@login_required
def link_my_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)

    if role_manager.is_master(user_id):
        return redirect(url_for('admin.user_master'))

    if user.company_id:
        return redirect(url_for('company.my_company'))

    args = form_checker.process(request, 'company_search_link_form')

    ref_company_id = args.pop('cid', None)
    ref_user_id = args.pop('uid', None)
    # TBI do something with ref_user_id? Notify when user joined
  
    if ref_company_id:
        # There are referrals
        if user.company_id: # User already in a company            
            if int(ref_company_id) == user.company_id:
                # Redirect to its own company
                return redirect(url_for('company.my_company'))
            else:
                # Leave old company and go to a new one
                company_old = db.company.get_by_id(user.company_id).to_public_dict()

                list_companies = [ (db.company.get_by_id(ref_company_id).to_public_dict()) ]
                
                return render_template('company/link_my_company.html', list_companies=list_companies,
                    current_page=1,
                    num_results=1,
                    num_pages=1, 
                    company_old=company_old)

        else:
            list_companies = [ (db.company.get_by_id(ref_company_id).to_public_dict()) ]
            return render_template('company/link_my_company.html', list_companies=list_companies,
                current_page=1,
                num_results=1,
                num_pages=1)
    # No referral or existing company case

    # Add form checker
    # Default type
    limit = int(args.pop('limit', 10))
    current_page = int(args.pop('current_page', 1))
    search_term = args.pop('search_term', '')

    list_companies = []
    if search_term.isdigit():
        # Search based on id
        try:
            list_companies = [ db.company.get_by_id(int(search_term)).to_public_dict() ]
        except ValueError:
            pass

    num_pages, companies, num_results = db.company.search(keyword=search_term, limit=limit, 
            current_page=current_page)
    
    list_companies = list_companies + [ comp.to_public_dict() for comp in companies ]
    pending_request = None

    # Obtain user's pending request
    if user.company_name:
        existing = db.role.filter_by(user_id=user_id, 
            operation=role_constants.OPERATION_GENERAL,
            permission=role_constants.REQUEST_PENDING)
            # Currently overwriting request
        pending_request = existing if existing else None


    return render_template('company/link_my_company.html', list_companies=list_companies,
        current_page=current_page,
        num_results=num_results,
        num_pages=num_pages,
        pending_request=pending_request)
    
    
@bp.route('/my-company-employees')
@login_required
def get_employee_list():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))
        
    # Checking for editing permission
    if not role_manager.check_permission(user_id, 
                role_constants.OPERATION_USER_MANAGEMENT, 
                role_constants.ACTION_VIEW):
        return abort(403) # Access denied
    
    # Obtaining employee lists
    company = user.company
    #employees = company.users 

    pending_requests = []
    
    employees_list = db.role.filter_by_q(company_id=user.company_id,
                    operation=role_constants.OPERATION_GENERAL).filter(
                    models.UserCompanyRole.permission >= role_constants.PERMISSION_ROLE_USER)
    employees = [ emp.to_user_dict() for emp in employees_list]
    
    # Limit permission levels
    current_user_permission = role_manager.get_permission_level(user_id)
    if current_user_permission >= role_constants.PERMISSION_ROLE_MANAGER:
        current_user_permission == role_manager.check_permission(user_id, 
                role_constants.OPERATION_USER_MANAGEMENT,
                role_constants.ACTION_UPDATE)
        # Obtain only verified email
        #pending_requests = (db.user.query().filter_by(company_name=str(company.id),company_id=None,is_account_confirmed=True)
        #)
        #pending_requests = (db.user.query().filter_by(company_name=str(company.id),company_id=None,is_account_confirmed=True)
        #        .join(models.UserCompanyRole).group_by(models.User))#.order_by(models.UserCompanyRole.create_time))
        pending = db.role.filter_by_q(company_id=user.company_id,operation=role_constants.OPERATION_GENERAL,
                permission=role_constants.REQUEST_PENDING).order_by('user_company_role.create_time desc')
                #.join(models.User).group_by(models.User)
        pending_requests = [ (req.user, req.create_time) for req in pending ]

    #employee_list = [ employee.to_public_dict() for employee in employees ]    
    return render_template('company/my_company_employees_rv.html', 
            company=company, 
            employees=employees, 
            permission_levels=role_constants.PERMISSION_TEXT_ARR,
            current_user_permission=current_user_permission,
            pending_requests=pending_requests)
    
    
@bp.route('/verify-company')
@login_required
def verify_company():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    company = user.company
    company_id = None
    verified = False

    if company:
        company_id = company.id
    else:
        company_id = user.company_name # user that have submitted link request
    
    if not company_id:
        return redirect(url_for('company.link_my_company'))

    company_verify = db.company_verify.filter_by(company_id=company_id)

    submitted_by_user = False # Check if current user has ever submitted a verify request

web/views/membership.py
from flask import Blueprint, render_template, request, abort, views, redirect, url_for, abort, flash, send_file
from flask_login import login_required, current_user, login_user
from werkzeug import secure_filename
from io import BytesIO
import xlsxwriter
from flask import current_app as app
from flask_babel import lazy_gettext

import database.models as models
from web import db, form_checker, role_manager, membership_manager, ds
from web.core import constants, geo
import database.enums as db_enums
from role import role_constants
from membership import membership_constants

bp = Blueprint('membership', __name__)

# Disabled - not allowing creating new company at the moment
# HShould be andled instead by views in register

@bp.route('/membership-info')
def membership_info():
    return render_template('membership/membership_info.html', 
        membership_tiers=membership_constants.TIER_LIMITS)


# Company associated to the current user
@bp.route('/my-company-membership')
@login_required
def my_company_membership():
    user_id = current_user.get_id()
    user = db.user.get_by_id(user_id)
    
    if not user.company_id: 
        # No company associated with current user
        return redirect(url_for('company.link_my_company'))
    
    # Obtaining company information
    company = user.company
    previous_memberships = membership_manager.get_all_memberships(user.company_id)
    return render_template('membership/membership_my_company.html', 
        company=company,
        previous_memberships=previous_memberships)

web/views/rfq.py
from flask import Blueprint, render_template, abort, request
from flask_login import current_user, login_required

from web import db, form_checker, role_manager

bp = Blueprint('rfq', __name__)

@bp.route('/create-rfq', methods=['GET'])
@login_required
def create_rfq():
    args = form_checker.process(request)
    product = args.get('product', '')    
    quantity = ''
    if args.get('quantity', None):
        quantity += f'{args.get("quantity")} '
    
    if args.get('unit', None):
        quantity += args.get('unit')
    
    return render_template('rfq/create_rfq.html', product=product, quantity=quantity)

@bp.route('/manage-rfqs')
@login_required
def manage_rfqs():
    rfqs = db.rfq.get_by_buyer_id(current_user.id)    
    return render_template('/rfq/manage_rfqs.html', rfqs=rfqs)

@bp.route('/rfq/<id_slug(model="rfq",attr="product"):pr_id>')
@login_required
def rfq_page(pr_id):
    rfq = db.rfq.get_by_id(pr_id)

    if not rfq:
        return abort(404)
    
    is_owner = False
    quotes = db.quote.get_by_rfq_id(rfq.id)

    if current_user.is_authenticated and rfq.buyer_id == current_user.id:
        is_owner = True
    else:
        quotes = [ x for x in quotes if x.seller_id == current_user.id ]
    
    return render_template('/rfq/rfq.html', 
                            rfq=rfq, 
                            quotes=quotes,
                            is_owner=is_owner)

@bp.route('/update-rfq/<id_slug(model="rfq",attr="product"):pr_id>')
@login_required
def update_rfq(pr_id):
    rfq = db.rfq.get_by_id(pr_id)

    if not rfq:
        return abort(404)

    if current_user.id != rfq.buyer_id:
        return abort(403)
    
    return render_template('/rfq/update_rfq.html', rfq=rfq)

@bp.route('/sourcing')
def sourcing():

    args = form_checker.process(request, 'search_rfq')
    keyword = args.pop('keyword', '')
    category = args.pop('category', None)
    limit = int(args.pop('limit', 20))
    current_page = int(args.pop('current_page', 1))    

    num_pages, rfqs = db.rfq.search(keyword=keyword, category=category, 
                                    limit=limit, current_page=current_page)

    categories = [('', 'All')] + (db.query(db.product_category.Model.id, db.product_category.Model.name)
                    .filter(db.product_category.Model.parent_category_id == None).all())    

    return render_template('/rfq/sourcing.html',
                            keyword=keyword,
                            category=category,
                            categories=categories,
                            current_page=current_page,
                            num_pages=num_pages,
                            rfqs=rfqs)

web/templates/components/admin.html
{% macro render_nav() %}
{% set items = [
    (_('Manage Users'), url_for('admin.user_master')),
    (_('Manage Companies'), url_for('admin.manage_companies')),
    (_('Resolve Tickets'), url_for('admin.resolve_tickets'))
    ] %}
<h3>{{ _('Admin Console') }}</h3>
<div class='admin-top-nav'>
    <ul class='nav nav-tabs'>
        {% for name, url in items %}
        <li class='nav-item'>
            <a href='{{ url }}' class='nav-link {% if request.path.startswith(url) %}active{% endif %}'>{{ name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endmacro %}

web/templates/components/footer.html
{% set footer_cols = [
    {
        "label": _('About Us'),
        "li_items": [
            [_('About {}'.format(config['APP_NAME'])), url_for("static_pages.about_page")],
            [_('Team'), url_for("static_pages.team_page")],
            [_('Careers'), url_for("static_pages.careers")],            
            [_('Sitemap'), url_for("static_pages.sitemap")],
            [_('Terms of Service'), url_for("static_pages.tos_page")],
            [_('Privacy Policy'), url_for("static_pages.privacy_page")],
        ]
    },
    {
        "label": _('Customer Services'),
        "li_items": [
            [_('Help'), url_for("static_pages.help")],
            [_('Contact Us'), url_for("static_pages.contact")],
            [_('Report an Abuse'), url_for("static_pages.report_abuse")],
            [_('Policy & Rules'), url_for("static_pages.policy_and_rules")]
        ]
    },
    {
        "label": _('Buy On ') + config['APP_NAME'],
        "li_items": [
            [_('Search Products'), url_for("search.search")],
            [_('Request for Quotation'), url_for("rfq.sourcing")]
        ]
    },
    {
        "label": _('Sell On ') + config['APP_NAME'],
        "li_items": [
            [_('Premium Membership Pricing'), url_for("membership.membership_info")],
            [_('Learning Center'), url_for("static_pages.learning_center")],
        ]
    },
    {
        "label": _('Trade Services'),
        "li_items": [
            [_('Company Verification'), url_for("static_pages.company_verification")],
            [_('Inspection Service'), url_for("static_pages.inspection_services")]
        ]
    }
    
] %}

<div class="footer">
<div class="footer-main">

<div class="row"><!-- row --> 
    {% for col in footer_cols %}    
    <div class="col-sm-12 col-md"><!-- widgets column left -->
        <ul class="list-unstyled clear-margins"><!-- widgets -->
           <li class="widget-container widget_nav_menu"><!-- widgets list -->
               <h5 class="title-widget">{{ col.label }}</h5>
               <ul>
                {% for name, url in col.li_items %}
                    <li><a href='{{ url }}'>{{ name }}</a></li>
                {% endfor %}
               </ul>
           </li>               
        </ul>                                                           
   </div><!-- widgets column left end -->

    {% endfor %}    
                
</div>

<div class="row">
    <div class="col-sm-12">
         © 2018, {{ config['APP_NAME'] }} Inc. {{ _('All Rights Reserved') }}.
    </div>
</div>

</div>
</div>

web/templates/components/footer_nav.html
<div class='footer-nav-content'>
    <table class='footer-nav-table'>
        <tr>
            <td>
                <a class='footer-nav-btn 
                    {% if request.path == url_for("home.default") %}active
                    {% endif %}' href='{{ url_for("home.default") }}'>
                    <i class='fa fa-home'></i>
                    <div>{{ _('Home') }}</div>
                </a>
            </td>
            <td>
                <a class='footer-nav-btn 123
                    {% if request.path.startswith(url_for("search.search")) %}active
                    {% endif %}' href='{{ url_for("search.search") }}'>
                    <i class='fa fa-search'></i>
                    <div>{{ _('Search') }}</div>
                </a>
            </td>            
            <td>
                <a class='footer-nav-btn 
                    {% if request.path.startswith(url_for("messages.home")) %}active
                    {% endif %}' href='{{ url_for("messages.home") }}'>
                    <i class='fa fa-comments'></i>
                    <div>{{ _('Messages') }}</div>
                </a>
            </td>
            <td>
                <a class='footer-nav-btn 
                    {% if request.path.startswith(url_for("account.my_account")) %}active
                    {% endif %}' href='{{ url_for("account.my_account") }}'>
                    <i class='fa fa-user'></i>
                    <div>{{ _('My account') }}</div>
                </a>
            </td>
        </tr>
    </table>
</div>

web/templates/components/media.html
{% macro render_media_grid(media) %}
{% if media %}
<div class='media-grid' id='media-grid'>
    {% for item in media %}
    {% if 'image' in item.file_type %}
    <div class='media-item' id='{{ item.id }}-media-item'>
        <a href='{{ item.url }}'>
            <img src='{{ item.thumbnail() }}' alt='{{ item.name }}' />
        </a>
    </div>
    {% else %}
    {{ item.file_type }}
    <div class='media-item' id='{{ item.id }}-media-item'>
        <a href='{{ item.url }}'>{{ item.name | fmt_media_file }}</a>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% else %}
<p>
    <i>Empty gallery.</i>
</p>
{% endif %}
{% endmacro %}

{% macro render_media(media) %}
{% if media %}
{% if 'image' in item.file_type %}
<div class='media-item'>
    <a href='{{ media.url }}'>
        <img src='{{ media.thumbnail() }}' alt='{{ media.name }}' />
    </a>
</div>
{% else %}
{{ item.file_type }}
<div class='media-item' id='{{ item.id }}-media-item'>
        <a href='{{ item.url }}'>{{ item.name | fmt_media_file }}</a>
</div>
{% endif %}
{% endif %}
{% endmacro %}

web/templates/components/membership.html
{% macro render_membership_tier(tier=None) %}
{% if tier %}
    {{ constants.TIER_TEXT_DICT[tier] }} <span class='tier-icon {{ constants.TIER_CSSCLASS_DICT[tier] }}'></span>
{% else %}
    {{ constants.TIER_TEXT_DICT[constants.mc.TIER_BASIC] }} <span class='tier-icon {{ constants.TIER_CSSCLASS_DICT[constants.mc.TIER_BASIC] }}'></span>
{% endif %}
{% endmacro %}


{% macro render_membership_badge(tier=None) %}
{% if tier %}
    <span class='membership-badge {{ constants.TIER_CSSCLASS_DICT[tier] }}'>
        {{ constants.TIER_TEXT_DICT[tier] }} <span class='tier-icon {{ constants.TIER_CSSCLASS_DICT[tier] }}'></span>
    </span>    
{% else %}
    <span class='membership-badge {{ constants.TIER_TEXT_DICT[constants.mc.TIER_BASIC]  }}'>
        {{ constants.TIER_TEXT_DICT[constants.mc.TIER_BASIC] }} <span class='tier-icon {{ constants.TIER_CSSCLASS_DICT[constants.mc.TIER_BASIC] }}'></span>
    </span>    
{% endif %}
{% endmacro %}

{% macro render_membership_plans() %}
<div class='row'>
    {% for tier in constants.MEMBERSHIP_TIERS %}
    {% set desc = constants.TIER_DESCRIPTIONS[tier] %}
    <div class='col-sm-12 col-md-3 mb-3'>
        <div class='card membership-grid-card {{ constants.TIER_CSSCLASS_DICT[tier] }}'>
            <div class='card-header text-center'>                
                <div class='tier-name'>{{ constants.TIER_NAME_DICT[tier] }}</div>
                <div class='tier-price'><span class='tier-price-unit'>$</span><span class='tier-price-value'>{{ desc.price }}</span></div>
                <div class='tier-price-note'>{{ desc.price_note }}</div>
                <div class='tier-getstart'>
                    <a href='{{ url_for("auth.register") }}' class='btn-light'>{{ _('Get Started') }}</a>
                </div>
            </div>
            <div class='card-body'>
                {% if desc.offer %}<p class='tier-offer'>{{ desc.offer }}</p><hr>{% endif %}                
                {% for item in desc.features %}
                {% if loop.index != 1 %}<hr>{% endif %}
                <p>{{ item }}</p>                
                {% endfor %}
            </div>
        </div>
    </div>    
    {% endfor %}
</div>
{% endmacro %}

web/templates/components/rfq.html
{% macro render_rfqs(rfqs) %}
<div class='rfqs-list'>
    {% if rfqs %}
    {% for rfq in rfqs %}
    <div class='mb-2 rfq-item' id='rfq-{{ rfq.id }}'>        
        <div class='rfq-item-pic float-left'>
                <img src="{% if rfq.media %} {{ rfq.media[0].thumbnail() }} {% else %}/static/img/product_default.png{% endif %}" />
        </div>
        <div class='rfq-item-content float-left card border-0'>
            <div class='card-body'>
                <div class='card-title'>
                    <h5>
                    <a href='{{ url_for("rfq.rfq_page", pr_id=rfq.id) }}'>
                        {{ rfq.product }}
                    </a>
                    </h5>
                </div>
                        
                <div class='card-text'>
                    {% for keyword in rfq.keywords %}
                    <span class='keyword'>{{ keyword }}</span>
                    {% endfor %}
                </div>
                <div class='card-text mt-1 mb-1'><i>{{ rfq.content|striptags|strip_spaces|fmt_title(numchars=150) }}</i></div>
                <div class='card-text category-path'>{{ rfq.product_category.path_as_str }}</div>
            </div>
        </div>

        <div class='float-right align-middle btn-box pt-2'>
            <a href='{{ url_for("rfq.update_rfq", pr_id=rfq.id) }}' class='float-right'>
                <span class='btn-update btn-sm'><i class='fa fa-pencil'></i></span>
            </a>
            <div class='text-muted float-left'>{{ _('Time left') }}: <span class='time-left'>{{ rfq.time_left_str }}</span></div>
            <div class='text-muted float-left'>{{ _('Quotes left') }}: <span class='quotes-left'>{{ rfq.quotes_left }}</span></div>       
            {% if rfq.is_expired %}
            <span class='rfq-status rfq-expired'>{{ _('Expired') }}</span>
            {% else %}
            <span class='rfq-status rfq-active'>{{ _('Active') }}</span>
            {% endif %}
        </div>
                   
    </div>
    {% endfor %}
    {% else %}
    <p>
        <i>{{ _('No RFQs found.') }}</i>
    </p>
    {% endif %}
</div>
{% endmacro %}

web/templates/components/trade_lead.html
{% set color_match_dict = {
    constants.LEAD_TYPE_BUY: 'buyer',
    constants.LEAD_TYPE_SELL: 'seller',
    constants.LEAD_TYPE_OTHER: ''
}

%}

{% macro render_trade_leads(trade_leads) %}
<div class='trade-leads-list'>
    {% if trade_leads %}
    {% for lead in trade_leads %}
    <div class='mb-2 rfq-item' id='trade-lead-{{ lead.id }}'>
        <div class='rfq-item-pic badge {{ color_match_dict[lead.lead_type] }} float-left'>
            
        </div>        
        <div class='rfq-item-pic float-left'>
                <img src="{% if lead.media %} {{ lead.media[0].thumbnail() }} {% else %}/static/img/product_default.png{% endif %}" />
        </div>
        <div class='rfq-item-content float-left card border-0'>
            <div class='card-body'>
                <div class='card-title'>
                    <h5>
                        <span class="badge badge-sm {{ color_match_dict[lead.lead_type] }} text-white">
                        {% if lead.lead_type == constants.LEAD_TYPE_BUY %}
                            {{ _('Buy') }}
                        {% elif lead.lead_type == constants.LEAD_TYPE_SELL %}
                            {{ _('Sell') }}
                        {% else %}
                            {{ _('Other')  }}
                        {% endif %}
                        </span>
                    <a href='{{ url_for("trade_lead.trade_lead_page", pr_id=lead.id) }}'>
                            {{ lead.title }}
                    </a>
                    </h5>
                </div>
                        
                <div class='card-text'>
                    {% for keyword in lead.keywords %}
                    <span class='keyword'>{{ keyword }}</span>
                    {% endfor %}
                    <i>{{ lead.content|striptags|strip_spaces|fmt_title(numchars=150) }}</i>
                </div>
                <div class='card-text category-path'>{{ lead.product_category.path_as_str }}</div>
            </div>
        </div>

        <div class='float-right align-middle btn-box pt-2'>
                <a href='{{ url_for("messages.trade_lead_thread_page", trade_lead_id=lead.id) }}' class='float-right'>
                        <span class='btn-primary btn-sm'><i class='fa fa-comments'></i></span>
                </a>
                <div class='float-right mr-2'>
                    <span class='btn-sm btn-success ' onclick='window.open_trade_lead_quickview(this);'
                                data-user_url='{{ url_for("account.account_page", pr_id=lead.user_id) }}' 
                                data-trade_lead_thread_url='{{ url_for("messages.trade_lead_thread_page", trade_lead_id=lead.id) }}'
                                data-trade_lead_id='{{ lead.id }}' data-trade_lead_url='{{ url_for("trade_lead.trade_lead_page", pr_id=lead.id) }}' 
                                data-trade_lead='{{ lead.to_dict()|tojson }}'>
                                <i class='fa fa-search-plus'></i>
                    </span>
                </div>
           {# <a href='{{ url_for("trade_lead.update_trade_lead", pr_id=lead.id) }}' class='float-right'>
                <span class='btn-update btn-sm'><i class='fa fa-pencil'></i></span> 
            </a> #}
            <div class='text-muted float-left'> {{ _('posted ') }} <span class='quotes-left'>{{ lead.create_time|fmt_datetime('short') }}</span></div>
        </div>
                   
    </div>
    {% endfor %}
    {% else %}
    <p>
        <i>{{ _('No Trade Lead Found.') }}</i>
    </p>
    {% endif %}
</div>
{% endmacro %}